<?php
$this->pageTitle('Login');
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'login')));
$form->prepare();
?>
<div id="login_wrapper">
   <?php echo $this->form()->openTag($form);?>
    <div class="login_row"><label class="login_label"><?php echo $form->get('email')->getLabel();?></label><?php echo $this->formElement($form->get('email'));?></div> 
     <div class="login_row"><label class="login_label"><?php echo $form->get('password')->getLabel();?></label><?php echo $this->formElement($form->get('password'));?></div>
      <div class="login_row"><?php echo $this->formSubmit($form->get('submit'));?></div> 
       <?php echo $this->form()->closeTag();?>
</div>


