<script type="text/javascript" src="/js/date.js"></script>
<script type="text/javascript" src="/js/jquery.datePicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/datePicker.css">
<script type="text/javascript">
    $(function()
    {
	$('.date-pick').datePicker({clickInput:true});
    });
</script>
<?php
$this->pageTitle('edit ticket');
$form = $this->form;
$form->setAttribute('action', $this->url('tickets', array('action' => 'edit', 'id' => $form->get('id')->getValue())));
$form->prepare();
//labels
$titleLabel = $form->get('title')->getLabel();
$ticketLabel = $form->get('ticket')->getLabel();
$prioLabel = $form->get('prio_id')->getLabel();
$assignLabel = $form->get('assign_id')->getLabel();
$projectLabel = $form->get('project_id')->getLabel();
$deadlineLabel = $form->get('deadline')->getLabel();
$departmentLabel = $form->get('department_id')->getLabel();
//elements
$titleElement = $this->formElement($form->get('title'));
$ticketElement = $this->formElement($form->get('ticket'));
$prioElement = $this->formElement($form->get('prio_id'));
$assignElement = $this->formElement($form->get('assign_id'));
$projectElement = $this->formElement($form->get('project_id'));
$deadlineElement = $this->formElement($form->get('deadline'));
$departmentElement = $this->formElement($form->get('department_id'));
$submit = $this->formSubmit($form->get('submit'));
?>

<div id="ticket_form_bg">
    <div class="ticket_head">Bearbeiten</div>
    <div id="ticket_form_wrapper">
        <?php echo $this->form()->openTag($form); ?>
         <div class="ticket_form_row">
            <label class="ticket_form_label ticket_title <?php echo ($this->formElementErrors($form->get('title'))) ? 'error' : '';?>">
                <?php echo $titleLabel;?>
            </label>
            <div class="ticket_form_element"><?php echo $titleElement;?></div>
        </div>
        
        <div class="ticket_form_row">
            <div class="ticket_form_selectbox">
             <label class="ticket_form_label  <?php echo ($this->formElementErrors($form->get('project_id'))) ? 'error' : '';?>">
                 <?php echo $projectLabel;?>
            </label>
                <div class="ticket_form_element "><?php echo $projectElement;?></div>
            </div>
            <div class="ticket_form_selectbox">
                <label class="ticket_form_label  <?php echo ($this->formElementErrors($form->get('department_id'))) ? 'error' : '';?>">
                    <?php echo $departmentLabel;?></label>
            <div class="ticket_form_element "><?php echo $departmentElement;?></div>
            </div>
            <div class="ticket_form_selectbox">
                <label class="ticket_form_label  <?php echo ($this->formElementErrors($form->get('assign_id'))) ? 'error' : '';?>">
                    <?php echo $assignLabel;?></label>
                <div class="ticket_form_element  "><?php echo $assignElement;?></div>
            </div>
             <div class="ticket_form_selectbox">
                <label class="ticket_form_label  <?php echo ($this->formElementErrors($form->get('prio_id'))) ? 'error' : '';?>">
                    <?php echo $prioLabel;?></label>
            <div class="ticket_form_element "><?php echo $prioElement;?></div>
            </div>
            <div class="ticket_form_selectbox">
                <label class="ticket_form_label ">
                    <?php echo $deadlineLabel;?></label>
            <div class="ticket_form_element "><?php echo $deadlineElement;?></div>
            </div>
             
        </div>
        <br>
        <div class="ticket_form_row">
           <div class="ticket_form_element"><?php echo $ticketElement;?></div>
        </div>
         <div class="ticket_form_row">
           <div class="ticket_form_element"><?php echo $submit;?></div>
        </div>
        
        <div id="clear"></div>
        <?php echo $this->formElement($form->get('assumed'));?>
        <?php echo $this->formElement($form->get('creator_id'));?>
        <?php echo $this->formElement($form->get('id'));?>
        <?php echo $this->formElement($form->get('status_id'));?>
        <?php echo $this->form()->closeTag();?>
    </div>
</div>

